// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZl0kNrQqtolDfldZP-6nggk-xWFVHBgY',
    appId: '1:851435752451:web:8d7aaa92283a5222be1236',
    messagingSenderId: '851435752451',
    projectId: 'pro-clean-app',
    authDomain: 'pro-clean-app.firebaseapp.com',
    storageBucket: 'pro-clean-app.appspot.com',
    measurementId: 'G-EMQLDPHQBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA87uPIa9q49fLRcxL5DkdsMarnizZfGd8',
    appId: '1:851435752451:android:d9fc50ba35486f5dbe1236',
    messagingSenderId: '851435752451',
    projectId: 'pro-clean-app',
    storageBucket: 'pro-clean-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj9D1lcl-5D0L46J7Jj2N1ByFjO80Ai6k',
    appId: '1:851435752451:ios:da7ff1ad053d6101be1236',
    messagingSenderId: '851435752451',
    projectId: 'pro-clean-app',
    storageBucket: 'pro-clean-app.appspot.com',
    iosBundleId: 'com.example.procleanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj9D1lcl-5D0L46J7Jj2N1ByFjO80Ai6k',
    appId: '1:851435752451:ios:da7ff1ad053d6101be1236',
    messagingSenderId: '851435752451',
    projectId: 'pro-clean-app',
    storageBucket: 'pro-clean-app.appspot.com',
    iosBundleId: 'com.example.procleanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZl0kNrQqtolDfldZP-6nggk-xWFVHBgY',
    appId: '1:851435752451:web:a728921fc83f3f10be1236',
    messagingSenderId: '851435752451',
    projectId: 'pro-clean-app',
    authDomain: 'pro-clean-app.firebaseapp.com',
    storageBucket: 'pro-clean-app.appspot.com',
    measurementId: 'G-FHWHL4LEK9',
  );

}