// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEsGbSX6bGYVrCA8IE9crvhrfEYsKOIHI',
    appId: '1:331505603027:web:14aba739973e52867bdf26',
    messagingSenderId: '331505603027',
    projectId: 'procleanapp-24a18',
    authDomain: 'procleanapp-24a18.firebaseapp.com',
    storageBucket: 'procleanapp-24a18.appspot.com',
    measurementId: 'G-FC6MDP0XY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Zd-z49-jsMtmHhZi76PfwQPs-patQs8',
    appId: '1:331505603027:android:b11056ae1bb0bd837bdf26',
    messagingSenderId: '331505603027',
    projectId: 'procleanapp-24a18',
    storageBucket: 'procleanapp-24a18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGuTyInBnw3HV0KDaHFXrc0sMX3y1ayl0',
    appId: '1:331505603027:ios:51b243d91557ceb77bdf26',
    messagingSenderId: '331505603027',
    projectId: 'procleanapp-24a18',
    storageBucket: 'procleanapp-24a18.appspot.com',
    iosBundleId: 'com.example.procleanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGuTyInBnw3HV0KDaHFXrc0sMX3y1ayl0',
    appId: '1:331505603027:ios:51b243d91557ceb77bdf26',
    messagingSenderId: '331505603027',
    projectId: 'procleanapp-24a18',
    storageBucket: 'procleanapp-24a18.appspot.com',
    iosBundleId: 'com.example.procleanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEsGbSX6bGYVrCA8IE9crvhrfEYsKOIHI',
    appId: '1:331505603027:web:417704c1c5d030337bdf26',
    messagingSenderId: '331505603027',
    projectId: 'procleanapp-24a18',
    authDomain: 'procleanapp-24a18.firebaseapp.com',
    storageBucket: 'procleanapp-24a18.appspot.com',
    measurementId: 'G-1F42MN7TL4',
  );

}